import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';

dotenv.config();

/**
 * IMPORTANT: This Supabase client is ONLY used for token verification purposes.
 * It does NOT access Supabase database or storage.
 * All data operations are performed with SQLite database.
 * 
 * This client's sole purpose is to verify JWT tokens generated by Supabase Auth.
 */

const supabaseUrl = process.env.SUPABASE_URL || 'https://vkappuaapscvteexogtp.supabase.co';
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || 'your_supabase_service_role_key_here';

// Create minimal Supabase client only for auth token verification
const supabase = createClient(supabaseUrl, supabaseServiceKey, {
  auth: {
    autoRefreshToken: false,
    persistSession: false
  }
});

// Export only the minimal client needed for auth verification
export default supabase;